import { UserProps } from "../../../types/admin";

export type SprintStatus = "upcoming" | "active" | "completed" | "archived";

export type Sprint = {
    sprintId: number;
    projectId: number;
    teamId: number | string | null;
    name: string;
    sequenceNumber: number;
    startDate: string;
    endDate: string;
    status: SprintStatus;
    isAutoGenerated: boolean;
    isDeleted: boolean;
    tsCreatedAt: string;
    tsUpdatedAt: string;
};

export type SprintConfig = {
    projectId: number;
    teamId: number | string | null;
    durationDays: number;
    anchorDate: string;
    autoRoll: boolean;
    upcomingHorizon: number;
};

export type ProjectSprintsResponse = {
    sprints: Sprint[];
    today: string;
};

export type MilestoneStatus = "Open" | "WIP" | "Pending" | "Closed" | "Deleted";

export type MilestoneAssignee = {
    userId: number | string | null;
    username: string | null;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    profileImageUrl: string | null;
};

export type Milestone = {
    milestoneId: number;
    // `taskId` is the milestone's backing TaskMaster row. The preview
    // pane uses it to load comments, notes, and attachments through the
    // same task-* endpoints a normal task uses, so a milestone behaves
    // like a "root task" with extra metadata (sprint linkage, multi
    // assignees). Null only for very legacy rows; the backend lazy-
    // backfills on the next read.
    taskId: number | null;
    // Human-readable id from the backing task's `display_id`
    // ("<code>-<n>"). Lets table / preview surfaces render the
    // friendly id without an extra lookup. Null for legacy
    // milestones whose backing task hasn't been backfilled yet.
    displayId?: string | null;
    projectId: number;
    teamId: number | string | null;
    sprintId: number | null;
    reporterId: number | string | null;
    // Resolved reporter user object (same shape as MilestoneAssignee)
    // so the milestone preview can render the reporter without an
    // extra team-member lookup. Optional for backwards compat.
    reporter?: MilestoneAssignee | null;
    title: string;
    description: unknown | null;
    status: MilestoneStatus | string;
    statusCode: number | null;
    priority: string | null;
    priorityCode: number | null;
    effortLevel?: string | null;
    effortLevelCode?: number | null;
    startDate: string | null;
    dueDate: string | null;
    tags: unknown | null;
    // External links shown by the milestone preview's URL/Link section.
    // Mirrors `TaskProps.links` shape: `{ id, url, title, isGitHub }[]`.
    // Stored as `JSONField` server-side; expressed as `unknown` here to
    // match the existing `tags` convention (the consumer narrows it).
    links?: unknown | null;
    isDeleted: boolean;
    tsCreatedAt: string;
    tsUpdatedAt: string;
    assignees: MilestoneAssignee[];
    tasksTotal?: number;
    tasksClosed?: number;
};

export type ProjectMilestonesResponse = {
    milestones: Milestone[];
};

export type MilestoneResponse = {
    milestone: Milestone;
};

export type SprintConfigResponse = {
    config: SprintConfig | null;
};

export type SprintResponse = {
    sprint: Sprint;
};

// `UserProps` is re-exported only as a convenience hint; the services
// import it directly from `types/admin`.
export type { UserProps };
