import { useEffect, useMemo, useState } from "react";
import AddIcon from "@mui/icons-material/Add";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import EditIcon from "@mui/icons-material/Edit";
import {
    Box,
    Button,
    Chip,
    DialogContent,
    DialogTitle,
    Divider,
    IconButton,
    Input,
    Modal,
    ModalDialog,
    Option,
    Select,
    Stack,
    Typography,
} from "@mui/joy";
import { useColorScheme } from "@mui/joy/styles";

import { AppTooltip } from "../../../../components/ui/AppTooltip";
import { SprintMilestoneManagementState } from "../../../../hooks/tasks/useSprintMilestoneManagement";
import { useTranslation } from "../../../../i18n";
import { taskMetaLabel } from "../../utils/taskMeta";
import { Sprint } from "../types";
import { DeleteSprintModal } from "./DeleteSprintModal";

const STATUS_COLOR: Record<string, string> = {
    Open: "#0044c2",
    WIP: "#ff8c00",
    Pending: "#b900ff",
    Closed: "#1dc200",
    Deleted: "#94a3b8",
};

type Props = {
    open: boolean;
    onClose: () => void;
    projectId: number;
    useSM: SprintMilestoneManagementState;
};

const todayIso = () => new Date().toISOString().slice(0, 10);

const sprintBucket = (s: Sprint, today: string): "past" | "current" | "upcoming" => {
    if (s.endDate < today) return "past";
    if (s.startDate <= today && today <= s.endDate) return "current";
    return "upcoming";
};

const SprintRow = ({
    sprint,
    projectId,
    useSM,
    sprints,
}: {
    sprint: Sprint;
    projectId: number;
    useSM: SprintMilestoneManagementState;
    sprints: Sprint[];
}) => {
    const { t } = useTranslation();
    const [editing, setEditing] = useState(false);
    const [name, setName] = useState(sprint.name);
    const [start, setStart] = useState(sprint.startDate);
    const [end, setEnd] = useState(sprint.endDate);
    const [error, setError] = useState<string | null>(null);
    const [confirmingDelete, setConfirmingDelete] = useState(false);

    useEffect(() => {
        setName(sprint.name);
        setStart(sprint.startDate);
        setEnd(sprint.endDate);
    }, [sprint.sprintId, sprint.name, sprint.startDate, sprint.endDate]);

    const milestonesInSprint = useMemo(() => {
        const list = useSM.projectMilestones[projectId] ?? [];
        return list.filter((m) => m.sprintId === sprint.sprintId);
    }, [useSM.projectMilestones, projectId, sprint.sprintId]);

    const otherSprints = useMemo(
        () => sprints.filter((s) => s.sprintId !== sprint.sprintId),
        [sprints, sprint.sprintId]
    );

    const save = async () => {
        setError(null);
        if (!start || !end || end < start) {
            setError(t.tasks.sprintManager.endBeforeStart);
            return;
        }
        const res = await useSM.updateExistingSprint({
            sprintId: sprint.sprintId,
            name,
            startDate: start,
            endDate: end,
        });
        if (res) {
            setEditing(false);
        } else {
            setError(t.tasks.sprintManager.updateFailed);
        }
    };

    const remove = () => setConfirmingDelete(true);

    return (
        <Box
            sx={{
                p: 1.25,
                borderRadius: 8,
                border: "1px solid",
                borderColor: "neutral.outlinedBorder",
                bgcolor: "background.surface",
            }}
        >
            <Stack alignItems="center" direction="row" spacing={1}>
                {editing ? (
                    <Input
                        size="sm"
                        sx={{ flex: 1 }}
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                    />
                ) : (
                    <Typography level="title-sm" sx={{ flex: 1 }}>
                        {sprint.name}
                    </Typography>
                )}
                <Chip color="neutral" size="sm" variant="soft">
                    #{sprint.sequenceNumber}
                </Chip>
                {sprint.isAutoGenerated && (
                    <Chip color="primary" size="sm" variant="soft">
                        {t.tasks.sprintManager.autoChip}
                    </Chip>
                )}
                {!editing && (
                    <AppTooltip size="sm" title={t.tasks.sprintManager.editTooltip}>
                        <IconButton size="sm" variant="plain" onClick={() => setEditing(true)}>
                            <EditIcon sx={{ fontSize: 16 }} />
                        </IconButton>
                    </AppTooltip>
                )}
                <AppTooltip size="sm" title={t.tasks.sprintManager.deleteTooltip}>
                    <IconButton color="danger" size="sm" variant="plain" onClick={remove}>
                        <DeleteOutlineIcon sx={{ fontSize: 16 }} />
                    </IconButton>
                </AppTooltip>
            </Stack>

            <Stack alignItems="center" direction="row" spacing={1} sx={{ mt: 1 }}>
                {editing ? (
                    <>
                        <Input
                            size="sm"
                            type="date"
                            value={start}
                            onChange={(e) => setStart(e.target.value)}
                        />
                        <Typography level="body-xs">→</Typography>
                        <Input
                            size="sm"
                            type="date"
                            value={end}
                            onChange={(e) => setEnd(e.target.value)}
                        />
                        <Button size="sm" onClick={save}>
                            {t.tasks.sprintManager.saveButton}
                        </Button>
                        <Button
                            color="neutral"
                            size="sm"
                            variant="plain"
                            onClick={() => {
                                setEditing(false);
                                setName(sprint.name);
                                setStart(sprint.startDate);
                                setEnd(sprint.endDate);
                                setError(null);
                            }}
                        >
                            {t.tasks.sprintManager.cancelButton}
                        </Button>
                    </>
                ) : (
                    <Typography level="body-xs" sx={{ color: "neutral.500" }}>
                        {sprint.startDate} → {sprint.endDate}
                    </Typography>
                )}
            </Stack>

            {error && (
                <Typography color="danger" level="body-xs" sx={{ mt: 0.5 }}>
                    {error}
                </Typography>
            )}

            <DeleteSprintModal
                milestoneCount={milestonesInSprint.length}
                open={confirmingDelete}
                sprintName={sprint.name}
                onClose={() => setConfirmingDelete(false)}
                onConfirm={async () => {
                    await useSM.removeSprint(sprint.sprintId, projectId);
                    setConfirmingDelete(false);
                }}
            />

            {milestonesInSprint.length > 0 && (
                <Box sx={{ mt: 1.25, pl: 1, borderLeft: "2px solid", borderColor: "divider" }}>
                    <Typography level="body-xs" sx={{ color: "neutral.500", mb: 0.5 }}>
                        {t.tasks.sprintManager.milestonesHeader}
                    </Typography>
                    <Stack spacing={0.5}>
                        {milestonesInSprint.map((m) => (
                            <Stack
                                key={m.milestoneId}
                                alignItems="center"
                                direction="row"
                                spacing={1}
                            >
                                <Typography level="body-sm" sx={{ flex: 1 }}>
                                    {m.title}
                                </Typography>
                                <Chip
                                    size="sm"
                                    variant="soft"
                                    sx={{
                                        color: STATUS_COLOR[m.status as string] ?? "#94a3b8",
                                        backgroundColor: `${STATUS_COLOR[m.status as string] ?? "#94a3b8"}1A`,
                                    }}
                                >
                                    {taskMetaLabel(m.status, t.tasks.filters)}
                                </Chip>
                                <Select
                                    placeholder={t.tasks.sprintManager.moveToPlaceholder}
                                    size="sm"
                                    sx={{ minWidth: 160 }}
                                    value={null}
                                    onChange={async (_, v) => {
                                        if (v === undefined || v === null) return;
                                        const target = v === -1 ? null : Number(v);
                                        await useSM.moveMilestone(
                                            m.milestoneId,
                                            target,
                                            projectId
                                        );
                                    }}
                                >
                                    <Option value={-1}>
                                        {t.tasks.sprintManager.noSprintOption}
                                    </Option>
                                    {otherSprints.map((s) => (
                                        <Option key={s.sprintId} value={s.sprintId}>
                                            {s.name}
                                        </Option>
                                    ))}
                                </Select>
                            </Stack>
                        ))}
                    </Stack>
                </Box>
            )}
        </Box>
    );
};

export const SprintManagerDialog = ({ open, onClose, projectId, useSM }: Props) => {
    const { t } = useTranslation();
    const { mode } = useColorScheme();
    const isDark = mode === "dark";
    const [showAdd, setShowAdd] = useState(false);
    const [adhocName, setAdhocName] = useState("");
    const [adhocStart, setAdhocStart] = useState(todayIso());
    const [adhocEnd, setAdhocEnd] = useState(todayIso());
    const [adhocError, setAdhocError] = useState<string | null>(null);
    const [creating, setCreating] = useState(false);

    const today = todayIso();
    const sprints = useSM.projectSprints[projectId] ?? [];

    const grouped = useMemo(() => {
        const out: Record<"past" | "current" | "upcoming", Sprint[]> = {
            past: [],
            current: [],
            upcoming: [],
        };
        for (const s of sprints) out[sprintBucket(s, today)].push(s);
        return out;
    }, [sprints, today]);

    useEffect(() => {
        if (!open) return;
        // Refresh sprints + milestones on open so the user always sees
        // the latest state, including newly auto-rolled rows.
        useSM.loadSprintsForProject(projectId);
        useSM.loadMilestonesForProject(projectId, {
            statuses: ["Open", "WIP", "Pending", "Closed"],
        });
    }, [open, projectId]);

    const submitAdhoc = async () => {
        setAdhocError(null);
        if (!adhocName || !adhocStart || !adhocEnd || adhocEnd < adhocStart) {
            setAdhocError(t.tasks.sprintManager.adhocRequired);
            return;
        }
        setCreating(true);
        const created = await useSM.createNewSprint({
            projectId,
            name: adhocName,
            startDate: adhocStart,
            endDate: adhocEnd,
        });
        setCreating(false);
        if (created) {
            setShowAdd(false);
            setAdhocName("");
            setAdhocStart(todayIso());
            setAdhocEnd(todayIso());
        } else {
            setAdhocError(t.tasks.sprintManager.adhocOverlap);
        }
    };

    const renderSection = (title: string, items: Sprint[]) => (
        <Box>
            <Typography
                level="body-xs"
                sx={{
                    fontWeight: 600,
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                    color: "neutral.500",
                    mb: 0.75,
                }}
            >
                {title} ({items.length})
            </Typography>
            <Stack spacing={1}>
                {items.length === 0 ? (
                    <Typography level="body-xs" sx={{ color: "neutral.400" }}>
                        {t.tasks.sprintManager.none}
                    </Typography>
                ) : (
                    items.map((s) => (
                        <SprintRow
                            key={s.sprintId}
                            projectId={projectId}
                            sprint={s}
                            sprints={sprints}
                            useSM={useSM}
                        />
                    ))
                )}
            </Stack>
        </Box>
    );

    return (
        <Modal open={open} onClose={onClose}>
            <ModalDialog
                className={`custom-scrollbar-${isDark ? "dark" : "light"}`}
                sx={{
                    width: { xs: "calc(100vw - 24px)", md: "auto" },
                    minWidth: { xs: 0, md: 640 },
                    maxWidth: { xs: "100vw", md: 800 },
                    maxHeight: { xs: "calc(100dvh - 32px)", md: "85vh" },
                    overflow: "auto",
                }}
            >
                <DialogTitle>{t.tasks.sprint.managerDialogTitle}</DialogTitle>
                <Divider />
                <DialogContent sx={{ overflowY: "auto" }}>
                    <Stack spacing={2.5} sx={{ pt: 1, pb: 1 }}>
                        <Stack alignItems="center" direction="row" spacing={1}>
                            <Typography level="body-sm" sx={{ flex: 1 }}>
                                {t.tasks.sprintManager.planIntro}
                            </Typography>
                            <Button
                                size="sm"
                                startDecorator={<AddIcon />}
                                onClick={() => setShowAdd((v) => !v)}
                            >
                                {t.tasks.sprintManager.addCustomSprint}
                            </Button>
                        </Stack>

                        {showAdd && (
                            <Box
                                sx={{
                                    p: 1.5,
                                    borderRadius: 8,
                                    border: "1px solid",
                                    borderColor: "neutral.outlinedBorder",
                                    bgcolor: "background.level1",
                                }}
                            >
                                <Stack spacing={1}>
                                    <Input
                                        placeholder={t.tasks.sprintManager.sprintNamePlaceholder}
                                        size="sm"
                                        value={adhocName}
                                        onChange={(e) => setAdhocName(e.target.value)}
                                    />
                                    <Stack alignItems="center" direction="row" spacing={1}>
                                        <Input
                                            size="sm"
                                            type="date"
                                            value={adhocStart}
                                            onChange={(e) => setAdhocStart(e.target.value)}
                                        />
                                        <Typography level="body-xs">→</Typography>
                                        <Input
                                            size="sm"
                                            type="date"
                                            value={adhocEnd}
                                            onChange={(e) => setAdhocEnd(e.target.value)}
                                        />
                                        <Button loading={creating} size="sm" onClick={submitAdhoc}>
                                            {t.tasks.sprintManager.createButton}
                                        </Button>
                                    </Stack>
                                    {adhocError && (
                                        <Typography color="danger" level="body-xs">
                                            {adhocError}
                                        </Typography>
                                    )}
                                </Stack>
                            </Box>
                        )}

                        {renderSection(t.tasks.sprintManager.sectionCurrent, grouped.current)}
                        {renderSection(t.tasks.sprintManager.sectionUpcoming, grouped.upcoming)}
                        {renderSection(t.tasks.sprintManager.sectionPast, grouped.past)}
                    </Stack>
                </DialogContent>
            </ModalDialog>
        </Modal>
    );
};
