import Box from '@mui/joy/Box';
import Typography from '@mui/joy/Typography';
import Avatar from '@mui/joy/Avatar';
import { GridColDef, GridRenderCellParams, GridRenderEditCellParams } from '@mui/x-data-grid';
import { randomCreatedDate, randomUpdatedDate } from '@mui/x-data-grid-generator';
import { Select, MenuItem, Chip } from "@mui/material";
import dayjs from "dayjs";
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline';
import AutorenewIcon from '@mui/icons-material/Autorenew';
import HighlightOffIcon from '@mui/icons-material/HighlightOff';

const hmlOptions = [
    { label: "High", value: "high", color: "#ff2e2e" },
    { label: "Medium", value: "medium", color: "#e58700" },
    { label: "Low", value: "low", color: "#2bc8ff" },
];
const getHMLOption = (value: string) => hmlOptions.find((option) => option.value === value);

const statusOptions = [
    { label: "Open", value: "open", color: "#2bc8ff", icon: <CheckCircleOutlineIcon style={{ color: "#2bc8ff" }} /> },
    { label: "WIP", value: "wip", color: "#e58700", icon: <AutorenewIcon style={{ color: "#e58700" }} /> },
    { label: "Closed", value: "closed", color: "#0adc00", icon: <CheckCircleOutlineIcon style={{ color: "#0adc00" }} /> },
    { label: "Deleted", value: "deleted", color: "#ff2e2e", icon: <HighlightOffIcon style={{ color: "#ff2e2e" }} /> },
];
const getStatusOption = (value: string) => statusOptions.find((option) => option.value === value);

const customTagOptions = [
    { label: "grey", color: "#aaaaaa" },
    { label: "red", color: "#ff2e2e" },
    { label: "yellow", color: "#e58700" },
    { label: "green", color: "#0adc00" },
];
const getCustomTagOption = (label: string) => customTagOptions.find((option) => option.label === label);

export const taskColumns: GridColDef<(typeof taskRows)[number]>[] = [
    {
        field: 'id',
        headerName: 'Task ID',
        headerClassName: 'task-col--header',
        width: 120,
    },
    {
        field: 'summary',
        headerName: 'Summary',
        headerClassName: 'task-col--header',
        width: 300,
        editable: true,
        headerAlign: 'center',
    },
    {
        field: 'assignee',
        headerName: 'Assignee',
        headerClassName: 'task-col--header',
        editable: false,
        sortable: false,
        width: 170,
        renderCell: (params) => (
            <Box
                textAlign='left'
                sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
                <Avatar size="sm">{params.row.assigneeEmail}</Avatar>
                <div>
                    <Typography level="body-xs">{params.row.assigneeName}</Typography>
                </div>
            </Box>
        ),
    },
    {
        field: 'priority',
        headerName: 'Priority',
        headerClassName: 'task-col--header',
        width: 100,
        editable: true,
        align: 'center',
        headerAlign: 'center',
        renderCell: (params: GridRenderCellParams) => {
            const option = getHMLOption(params.value);
            const color = option?.color;
            return option ? <Chip
                label={option.label}
                variant="outlined"
                sx={{ color: color, opacity: 0.95 }} /> : null;
        },
        renderEditCell: (params: GridRenderEditCellParams) => (
            <Select
                value={params.value}
                onChange={(event) =>
                    params.api.setEditCellValue({ id: params.id, field: params.field, value: event.target.value })
                }
                fullWidth
            >
                {hmlOptions.map((option) => (
                    <MenuItem key={option.value} value={option.value}>
                        <Chip
                            label={option.label}
                            variant="outlined"
                            sx={{
                                color: option.color,
                                fontWeight: 'bold',
                                backgroundColor: 'transparent'
                            }} />
                    </MenuItem>
                ))}
            </Select>
        ),
    },
    {
        field: 'effortLevel',
        headerName: 'Effort Level',
        headerClassName: 'task-col--header',
        width: 100,
        editable: true,
        align: 'center',
        headerAlign: 'center',
        renderCell: (params: GridRenderCellParams) => {
            const option = getHMLOption(params.value);
            const color = option?.color;
            return option ? <Chip
                label={option.label}
                variant="outlined"
                sx={{ color: color, opacity: 0.95 }} /> : null;
        },
        renderEditCell: (params: GridRenderEditCellParams) => (
            <Select
                value={params.value}
                onChange={(event) =>
                    params.api.setEditCellValue({ id: params.id, field: params.field, value: event.target.value })
                }
                fullWidth
            >
                {hmlOptions.map((option) => (
                    <MenuItem key={option.value} value={option.value}>
                        <Chip
                            label={option.label}
                            variant="outlined"
                            sx={{
                                color: option.color,
                                fontWeight: 'bold',
                                backgroundColor: 'transparent'
                            }} />
                    </MenuItem>
                ))}
            </Select>
        ),
    },
    {
        field: 'status',
        headerName: 'Status',
        headerClassName: 'task-col--header',
        width: 120,
        editable: true,
        align: 'center',
        headerAlign: 'center',
        renderCell: (params: GridRenderCellParams) => {
            const option = getStatusOption(params.value);
            const color = option?.color;
            return option ? <Chip
                icon={option.icon}
                label={option.label}
                variant="outlined"
                sx={{ color: color, opacity: 0.95 }} /> : null;
        },
        renderEditCell: (params: GridRenderEditCellParams) => (
            <Select
                value={params.value}
                onChange={(event) =>
                    params.api.setEditCellValue({ id: params.id, field: params.field, value: event.target.value })
                }
                fullWidth
            >
                {statusOptions.map((option) => (
                    <MenuItem key={option.value} value={option.value}>
                        <Chip
                            icon={option.icon}
                            label={option.label}
                            variant="outlined"
                            sx={{
                                color: option.color,
                                fontWeight: 'bold',
                                backgroundColor: 'transparent'
                            }} />
                    </MenuItem>
                ))}
            </Select>
        ),
    },
    {
        field: 'createdDate',
        headerName: 'Created On',
        headerClassName: 'task-col--header',
        type: 'date',
        width: 100,
        align: 'center',
        headerAlign: 'center',
        valueFormatter: (params) => dayjs(params).format("YYYY-MM-DD"),
    },
    {
        field: 'dueDate',
        headerName: 'Due Date',
        headerClassName: 'task-col--header',
        type: 'date',
        editable: true,
        width: 100,
        align: 'center',
        headerAlign: 'center',
        valueFormatter: (params) => dayjs(params).format("YYYY-MM-DD"),
    },
    {
        field: 'daysLeft',
        headerName: 'Days Left',
        headerClassName: 'task-col--header',
        type: 'number',
        width: 100,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'parentTaskId',
        headerName: 'Parent Task ID',
        headerClassName: 'task-col--header',
        width: 120,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: 'customTag',
        headerName: 'Tag',
        headerClassName: 'task-col--header',
        width: 150,
        editable: true,
        align: 'center',
        headerAlign: 'center',
        renderCell: (params: GridRenderCellParams) => {
            const option = getCustomTagOption(params.value);
            const color = option?.color;
            return option ? <Chip
                label={option.label}
                variant="outlined"
                sx={{ color: color, opacity: 0.95 }} /> : null;
        },
        renderEditCell: (params: GridRenderEditCellParams) => (
            <Select
                value={params.value}
                onChange={(event) =>
                    params.api.setEditCellValue({ id: params.id, field: params.field, value: event.target.value })
                }
                fullWidth
            >
                {customTagOptions.map((option) => (
                    <MenuItem key={option.label} value={option.label}>
                        <Chip
                            label={option.label}
                            variant="outlined"
                            sx={{
                                color: option.color,
                                fontWeight: 'bold',
                                backgroundColor: 'transparent'
                            }} />
                    </MenuItem>
                ))}
            </Select>
        ),
    },
];

export const taskRows = [
    {
        id: 'INV-1234',
        summary: '/Users/kamikenpro/git/chat-app-prototype/frontend/weikiy/src/tasks/taskMain.tsx',
        priority: 'high',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1233',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "INV-1234",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1232',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1231',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1230',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1229',
        summary: 'ABC',
        priority: 'low',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1228',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1227',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1226',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1225',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1224',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1223',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1221',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1220',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1219',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1218',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1217',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-1216',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0234',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0233',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0232',
        summary: 'ABC',
        priority: 'low',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0231',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0230',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0229',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0228',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0227',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0226',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0225',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0224',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0223',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0221',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0220',
        summary: 'ABC',
        priority: 'low',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0219',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0218',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0217',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INV-0216',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1234',
        summary: '/Users/kamikenpro/git/chat-app-prototype/frontend/weikiy/src/tasks/taskMain.tsx',
        priority: 'high',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1233',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "INV-1234",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1232',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1231',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1230',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1229',
        summary: 'ABC',
        priority: 'low',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1228',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1227',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1226',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1225',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1224',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1223',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1221',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'deleted',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1220',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1219',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1218',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1217',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-1216',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0234',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0233',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0232',
        summary: 'ABC',
        priority: 'low',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0231',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0230',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0229',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0228',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0227',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0226',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0225',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0224',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0223',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0221',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'open',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0220',
        summary: 'ABC',
        priority: 'low',
        effortLevel: 'medium',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0219',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0218',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'low',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0217',
        summary: 'ABC',
        priority: 'medium',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'wip',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },
    {
        id: 'INW-0216',
        summary: 'ABC',
        priority: 'high',
        effortLevel: 'high',
        createdDate: randomCreatedDate(),
        dueDate: randomUpdatedDate(),
        daysLeft: '2',
        status: 'closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        customTag: "",
        customTagColor: "",
    },

];
