export const tasks = [
    {
        id: 'INV-1234',
        summary: '/Users/kamikenpro/git/chat-app-prototype/frontend/weikiy/src/tasks/taskMain.tsx',
        priority: 'High',
        effortLevel: 'Medium',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Deleted',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1233',
        summary: 'ABC',
        priority: 'Medium',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "INV-1234",
        emptyColumn: "",
    },
    {
        id: 'INV-1232',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Deleted',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1231',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Deleted',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1230',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1229',
        summary: 'ABC',
        priority: 'Low',
        effortLevel: 'Medium',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1228',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Deleted',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1227',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1226',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1225',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1224',
        summary: 'ABC',
        priority: 'Medium',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1223',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1221',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Deleted',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1220',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1219',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1218',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1217',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-1216',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0234',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Open',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0233',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0232',
        summary: 'ABC',
        priority: 'Low',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Open',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0231',
        summary: 'ABC',
        priority: 'Medium',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Open',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0230',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0229',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0228',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Open',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0227',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Medium',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0226',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0225',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'O',
        assigneeName: 'Olivia Ryhe',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0224',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'S',
        assigneeName: 'Steve Hampton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0223',
        summary: 'ABC',
        priority: 'Medium',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'C',
        assigneeName: 'Ciaran Murray',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0221',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Open',
        assigneeEmail: 'M',
        assigneeName: 'Maria Macdonald',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0220',
        summary: 'ABC',
        priority: 'Low',
        effortLevel: 'Medium',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'C',
        assigneeName: 'Charles Fulton',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0219',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'J',
        assigneeName: 'Jay Hooper',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0218',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'Low',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'K',
        assigneeName: 'Krystal Stevens',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0217',
        summary: 'ABC',
        priority: 'Medium',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'WIP',
        assigneeEmail: 'S',
        assigneeName: 'Sachin Flynn',
        parentTaskId: "",
        emptyColumn: "",
    },
    {
        id: 'INV-0216',
        summary: 'ABC',
        priority: 'High',
        effortLevel: 'High',
        createdDate: 'Feb 3, 2023',
        dueDate: 'Feb 5, 2023',
        daysLeft: '2',
        status: 'Closed',
        assigneeEmail: 'B',
        assigneeName: 'Bradley Rosales',
        parentTaskId: "",
        emptyColumn: "",
    },
];
