import { ArrowLeft, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";

/**
 * `/developers` — the public API, webhook and WebSocket reference.
 *
 * Public and auth-free, same shell as `/legal` and `/privacy`: an
 * integrator evaluating Genos has no account yet, so anything they need
 * in order to decide has to be readable without one.
 *
 * **Hand-rendered rather than a bundled Swagger UI.** The interactive
 * explorer is ~1MB and this file sits in the marketing bundle, which has
 * a documented entry-critical-path budget. The machine-readable document
 * is still published — `openapi.json` below is generated by the API
 * itself and is the source of truth for the REST half; this page is the
 * human-readable companion, not a second copy of the schema.
 *
 * Keep in sync with:
 *   - `genos-api/origin/views/public/openapi.py` (REST — has a drift test)
 *   - `genos-sockets/WEBSOCKET_EVENTS.md`        (WS events + rooms)
 *   - `genos-api/origin/models/common/webhook_models.py` (event catalog)
 */

const API_BASE = import.meta.env.VITE_DJANGO_URL || "https://api.genosai.dev";
const SPEC_URL = `${API_BASE}/api/public/v1/openapi.json`;

type Row = { name: string; meaning: React.ReactNode };

const Card = ({
    title,
    subtitle,
    children,
}: {
    title: string;
    subtitle?: string;
    children: React.ReactNode;
}) => (
    <section className="mt-10">
        <h2 className="text-xl font-black text-slate-900 dark:text-white">{title}</h2>
        {subtitle && <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{subtitle}</p>}
        <div className="mt-4">{children}</div>
    </section>
);

const Code = ({ children }: { children: React.ReactNode }) => (
    <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-[0.8125rem] text-violet-700 dark:bg-slate-800 dark:text-violet-300">
        {children}
    </code>
);

const Pre = ({ children }: { children: string }) => (
    <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 p-4 font-mono text-[0.8125rem] leading-6 text-slate-100 dark:bg-black/60">
        {children}
    </pre>
);

const Table = ({ rows, head }: { rows: Row[]; head: [string, string] }) => (
    <div className="mt-3 overflow-x-auto">
        <table className="w-full min-w-[34rem] border-collapse text-left text-sm">
            <thead>
                <tr className="border-b border-slate-200 dark:border-slate-700">
                    <th className="py-2 pr-4 font-semibold text-slate-500 dark:text-slate-400">
                        {head[0]}
                    </th>
                    <th className="py-2 font-semibold text-slate-500 dark:text-slate-400">
                        {head[1]}
                    </th>
                </tr>
            </thead>
            <tbody>
                {rows.map((r) => (
                    <tr key={r.name} className="border-b border-slate-100 dark:border-slate-800">
                        <td className="py-2 pr-4 align-top whitespace-nowrap">
                            <Code>{r.name}</Code>
                        </td>
                        <td className="py-2 align-top text-slate-600 dark:text-slate-300">
                            {r.meaning}
                        </td>
                    </tr>
                ))}
            </tbody>
        </table>
    </div>
);

const REST_ROWS: Row[] = [
    {
        name: "GET /api/public/v1/me/",
        meaning: "Who this key belongs to, and what it may do. The first call to make.",
    },
    {
        name: "GET /api/public/v1/projects/",
        meaning: "Projects you belong to — not the whole team.",
    },
    {
        name: "GET /api/public/v1/tasks/",
        meaning:
            "Tasks, filterable by project. Paged with limit / offset; limit is capped server-side.",
    },
    { name: "POST /api/public/v1/tasks/", meaning: "Create a task. Needs a write-scope key." },
    { name: "GET /api/public/v1/tasks/{id}/", meaning: "One task." },
    {
        name: "PATCH /api/public/v1/tasks/{id}/",
        meaning: "Update title, status or priority. Needs a write-scope key.",
    },
];

const WEBHOOK_ROWS: Row[] = [
    { name: "task.created", meaning: "A task was created." },
    {
        name: "task.updated",
        meaning: "A task changed. One event per task per action, not one per field.",
    },
    { name: "task.completed", meaning: "A task moved into a closed status." },
    {
        name: "task.comment_created",
        meaning: "Someone commented on a task. Carries the comment body.",
    },
    {
        name: "message.created",
        meaning: (
            <>
                A chat message was posted. Carries <Code>body_text</Code>. Requires an explicit
                channel list — see below.
            </>
        ),
    },
];

const WS_CHANNEL_ROWS: Row[] = [
    { name: "message.created", meaning: "New message in the channel." },
    { name: "message.updated", meaning: "Message edited." },
    { name: "message.deleted", meaning: "Message tombstoned." },
    { name: "message.reply_count_changed", meaning: "A thread gained or lost a reply." },
    { name: "reaction.added", meaning: "Reaction added." },
    { name: "reaction.removed", meaning: "Reaction removed." },
    { name: "channel.updated", meaning: "Title, avatar or settings changed." },
    { name: "channel.member_added", meaning: "Someone joined." },
    {
        name: "channel.member_removed",
        meaning: "Someone left or was removed (also sent to that user).",
    },
    { name: "typing", meaning: "Transient typing indicator. Not persisted." },
];

const WS_USER_ROWS: Row[] = [
    {
        name: "activity.created",
        meaning: "A notification for you — mention, assignment, reply. One per recipient.",
    },
    { name: "channel.created", meaning: "You were added to a new channel." },
    { name: "read.advanced", meaning: "Your read cursor moved (from any of your devices)." },
    { name: "pin.added", meaning: "A message was pinned." },
    { name: "pin.removed", meaning: "A pin was removed." },
    { name: "flag.added", meaning: "You flagged a message." },
    { name: "flag.removed", meaning: "You cleared a flag." },
];

const WS_TEAM_ROWS: Row[] = [
    { name: "presence.changed", meaning: "A teammate came online or went offline." },
];

export default function DevelopersPage() {
    return (
        <main className="min-h-screen bg-[linear-gradient(180deg,#ffffff_0%,#faf7ff_44%,#ffffff_100%)] px-4 py-10 text-slate-950 sm:px-6 lg:px-8 dark:bg-[linear-gradient(180deg,#020617_0%,#111827_48%,#020617_100%)] dark:text-white">
            <div className="mx-auto max-w-3xl">
                <Link
                    className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-violet-700 dark:text-slate-400 dark:hover:text-white"
                    to="/home"
                >
                    <ArrowLeft className="h-4 w-4" />
                    Genos
                </Link>

                <h1 className="mt-6 text-2xl font-black sm:text-3xl">Developers</h1>
                <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
                    REST API, outbound webhooks, and the realtime event stream.
                </p>

                <a
                    className="mt-5 inline-flex items-center gap-2 rounded-lg border border-violet-200 bg-white px-3.5 py-2 text-sm font-semibold text-violet-700 transition hover:bg-violet-50 dark:border-violet-500/40 dark:bg-slate-900 dark:text-violet-300 dark:hover:bg-slate-800"
                    href={SPEC_URL}
                    rel="noreferrer"
                    target="_blank"
                >
                    openapi.json
                    <ExternalLink className="h-3.5 w-3.5" />
                </a>
                <p className="mt-2 text-xs text-slate-400 dark:text-slate-500">
                    Served by the API itself, so it can never fall behind these pages. Import it
                    into Postman, Insomnia or your generator of choice.
                </p>

                <Card
                    title="Authentication"
                    subtitle="Create a key in Settings → Developer. It is shown once."
                >
                    <Pre>{`curl ${API_BASE}/api/public/v1/me/ \\
  -H "Authorization: ApiKey gnos_xxxxxxxxxxxxxxxxxxxxxxxx"`}</Pre>
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        The scheme is <Code>ApiKey</Code>, not <Code>Bearer</Code> — a key must
                        never be mistaken for a session token by anything that only looks for{" "}
                        <Code>Bearer</Code>.
                    </p>
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        A key is either a <b>personal access token</b> (acts as you, across every
                        team you belong to — so <Code>team_id</Code> is required wherever a team
                        must be chosen) or <b>team-scoped</b> (bound to one team, which is then
                        implied). Writes additionally need a key created with <Code>write</Code>{" "}
                        scope; a read key gets <Code>403</Code>, never a silent no-op.
                    </p>
                </Card>

                <Card title="REST" subtitle="Everything under /api/public/v1/.">
                    <Table head={["Endpoint", "What it does"]} rows={REST_ROWS} />
                    <p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        A task you cannot see and a task that does not exist both answer{" "}
                        <Code>404</Code>, deliberately — otherwise ids could be probed for
                        existence.
                    </p>
                </Card>

                <Card
                    title="Webhooks"
                    subtitle="Genos POSTs to your URL when something happens. Configure in Settings → Developer."
                >
                    <Table head={["Event", "Fires when"]} rows={WEBHOOK_ROWS} />

                    <h3 className="mt-8 text-base font-bold text-slate-800 dark:text-slate-100">
                        Scope: which objects you hear about
                    </h3>
                    <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        Subscribing to an event type does not have to mean the whole team. An
                        endpoint carries two filters, and they deliberately behave differently:
                    </p>
                    <Pre>{`project_ids: []            → every project      (a filter, unset)
project_ids: [12, 15]      → only those projects

channel_ids: []            → NO channel         (an allow-list, empty)
channel_ids: ["<uuid>"]    → only those channels`}</Pre>
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        Task events default to the whole team, because task metadata to a team-wide
                        subscriber is the ordinary case. <b>Chat does not.</b> A chat payload
                        carries what people actually wrote, and a webhook is configured by one
                        admin on behalf of everyone who talks in that channel — so{" "}
                        <Code>message.created</Code> requires you to name the channels explicitly.
                        There is no subscribe-to-all-chat.
                    </p>
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        <b>Direct messages can never be subscribed to.</b> A group channel has
                        visible, shared membership; a private one-to-one does not. Naming a DM is
                        rejected at subscribe time.
                    </p>

                    <h3 className="mt-8 text-base font-bold text-slate-800 dark:text-slate-100">
                        Verifying a delivery
                    </h3>
                    <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        Every request carries <Code>X-Genos-Signature</Code>,{" "}
                        <Code>X-Genos-Timestamp</Code>, <Code>X-Genos-Event</Code> and{" "}
                        <Code>X-Genos-Delivery</Code> — the last being a stable id you can use to
                        make your handler idempotent across retries. Recompute the HMAC over{" "}
                        <Code>{"<timestamp>.<raw body>"}</Code> with your endpoint secret and
                        compare in constant time. The timestamp is inside the signed string, so a
                        captured delivery cannot be replayed later.
                    </p>
                    <Pre>{`signed = f"{timestamp}.".encode() + raw_body
expected = "sha256=" + hmac.new(secret.encode(), signed, hashlib.sha256).hexdigest()
hmac.compare_digest(expected, request.headers["X-Genos-Signature"])`}</Pre>
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        Reply <Code>2xx</Code> quickly and do your work afterwards. Failures retry
                        with exponential backoff; an endpoint that keeps failing is disabled and
                        shown as such in Settings.
                    </p>
                </Card>

                <Card
                    title="Realtime (WebSocket)"
                    subtitle="Socket.IO. Present your access token on connect; the server resolves the user from the token, never from a client-supplied id."
                >
                    <p className="text-sm leading-7 text-slate-600 dark:text-slate-300">
                        Events are delivered into <b>rooms</b>, and the room an event uses tells
                        you its audience. This is the same idea as webhook scope, one layer down.
                    </p>

                    <h3 className="mt-6 text-base font-bold text-slate-800 dark:text-slate-100">
                        Channel room — everyone in that conversation
                    </h3>
                    <Table head={["Event", "Meaning"]} rows={WS_CHANNEL_ROWS} />

                    <h3 className="mt-8 text-base font-bold text-slate-800 dark:text-slate-100">
                        User room — only you, on all your devices
                    </h3>
                    <Table head={["Event", "Meaning"]} rows={WS_USER_ROWS} />
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        <Code>activity.created</Code> is per-recipient: one event per person
                        notified. That is why it is a realtime event and <i>not</i> a webhook — a
                        webhook subscriber would receive N copies of one message and have to
                        de-duplicate them.
                    </p>

                    <h3 className="mt-8 text-base font-bold text-slate-800 dark:text-slate-100">
                        Team room — everyone in the workspace
                    </h3>
                    <Table head={["Event", "Meaning"]} rows={WS_TEAM_ROWS} />

                    <p className="mt-6 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        After a reconnect, use <Code>resync</Code> to catch up rather than
                        replaying: it returns missed state as <Code>resync.batch</Code> pages.
                    </p>
                </Card>

                <Card title="Stability" subtitle="What we promise not to break.">
                    <p className="text-sm leading-7 text-slate-600 dark:text-slate-300">
                        Everything under <Code>/api/public/</Code> is a contract. Event names are
                        part of it — an integrator writes{" "}
                        <Code>if event == &quot;task.created&quot;</Code>, so renaming one is a
                        breaking change and will not happen inside a version. New fields may be
                        added to a payload; treat unknown fields as ignorable.
                    </p>
                    <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
                        <Code>/api/v2/</Code> and <Code>/api/v3/</Code> are internal surfaces that
                        change whenever the app needs them to. They are not part of this contract,
                        and building on them is not supported.
                    </p>
                </Card>

                <p className="mt-12 text-xs text-slate-400 dark:text-slate-500">
                    © {new Date().getFullYear()} Genos
                </p>
            </div>
        </main>
    );
}
