/**
 * A sprint's `status` (upcoming/active/completed) is derived server-side
 * from *today's date* on every `/sprint/list/` request, so the "active"
 * sprint rotates at a sprint boundary. The frontend otherwise loads
 * sprints only on project change and freezes them, which meant a tab left
 * open across midnight kept showing the previous sprint as "active" in the
 * milestone sprint picker and the dashboard until a hard refresh.
 *
 * `loadSprintsForProject` is the single reconciliation point. These tests
 * pin the reload behavior it now owns:
 *   - the default `currentSprint` follows the active-sprint rotation on a
 *     reload,
 *   - an explicit user pick is NOT overridden by that rotation,
 *   - a failed refresh never blanks out already-loaded sprints.
 */

import { act, renderHook } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { Sprint } from "../features/tasks/sprint-milestone/types";
import { useSprintMilestoneManagement } from "../hooks/tasks/useSprintMilestoneManagement";

// The hook imports the services barrel; keep every real export and override
// only the one network call these tests drive.
const loadProjectSprintsMock = vi.fn();
vi.mock("../features/tasks/sprint-milestone/services", async (importOriginal) => ({
    ...(await importOriginal<object>()),
    loadProjectSprints: (...args: unknown[]) => loadProjectSprintsMock(...args),
}));

const PROJECT_ID = 1;

const sprint = (
    sprintId: number,
    status: Sprint["status"],
    overrides: Partial<Sprint> = {}
): Sprint => ({
    sprintId,
    projectId: PROJECT_ID,
    teamId: null,
    name: `Sprint ${sprintId}`,
    sequenceNumber: sprintId,
    startDate: "2026-08-01",
    endDate: "2026-08-14",
    status,
    isAutoGenerated: true,
    isDeleted: false,
    tsCreatedAt: "2026-08-01T00:00:00Z",
    tsUpdatedAt: "2026-08-01T00:00:00Z",
    ...overrides,
});

// Queue the payload the next `loadSprintsForProject` call resolves to.
const nextResponse = (sprints: Sprint[] | undefined) => {
    loadProjectSprintsMock.mockResolvedValueOnce(
        sprints === undefined ? undefined : { sprints, today: "2026-08-10" }
    );
};

const renderSM = () => renderHook(() => useSprintMilestoneManagement("tok"));

const reload = async (hook: ReturnType<typeof renderSM>) => {
    await act(async () => {
        await hook.result.current.loadSprintsForProject(PROJECT_ID);
    });
};

beforeEach(() => {
    loadProjectSprintsMock.mockReset();
});

describe("useSprintMilestoneManagement — active sprint rotation", () => {
    it("defaults currentSprint to the active sprint on first load", async () => {
        const hook = renderSM();
        nextResponse([sprint(1, "completed"), sprint(2, "active"), sprint(3, "upcoming")]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.sprintId).toBe(2);
    });

    it("falls back to the first upcoming sprint when none is active yet", async () => {
        const hook = renderSM();
        nextResponse([sprint(1, "completed"), sprint(2, "upcoming"), sprint(3, "upcoming")]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.sprintId).toBe(2);
    });

    it("rotates the auto-selected sprint to the new active one on reload (the bug)", async () => {
        const hook = renderSM();
        // Day 1: sprint 1 is active → auto-selected.
        nextResponse([sprint(1, "active"), sprint(2, "upcoming")]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.sprintId).toBe(1);

        // Day 2: the server now reports sprint 1 completed, sprint 2 active.
        // A background reload must follow the rotation — no page refresh.
        nextResponse([sprint(1, "completed"), sprint(2, "active")]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.sprintId).toBe(2);
        expect(hook.result.current.currentSprint?.status).toBe("active");
    });

    it("does not override a sprint the user explicitly picked", async () => {
        const hook = renderSM();
        // Auto-selects sprint 2 (active).
        nextResponse([sprint(1, "completed"), sprint(2, "active"), sprint(3, "upcoming")]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.sprintId).toBe(2);

        // User navigates to inspect the past sprint 1 in the dashboard.
        act(() => hook.result.current.setCurrentSprint(sprint(1, "completed")));
        expect(hook.result.current.currentSprint?.sprintId).toBe(1);

        // A later reload where sprint 3 has become active must leave the
        // user's explicit choice (sprint 1) in place.
        nextResponse([sprint(1, "completed"), sprint(2, "completed"), sprint(3, "active")]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.sprintId).toBe(1);
    });

    it("refreshes the selected sprint's stale object even when the id is unchanged", async () => {
        const hook = renderSM();
        nextResponse([sprint(1, "active", { name: "Sprint 1" })]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.name).toBe("Sprint 1");

        // Same active sprint, but its server-side fields changed (renamed,
        // extended). The reload should swap in the fresh object.
        nextResponse([sprint(1, "active", { name: "Sprint 1 (renamed)", endDate: "2026-08-21" })]);
        await reload(hook);
        expect(hook.result.current.currentSprint?.name).toBe("Sprint 1 (renamed)");
        expect(hook.result.current.currentSprint?.endDate).toBe("2026-08-21");
    });

    it("keeps existing sprints when a background refresh fails", async () => {
        const hook = renderSM();
        nextResponse([sprint(1, "completed"), sprint(2, "active")]);
        await reload(hook);
        expect(hook.result.current.projectSprints[PROJECT_ID]).toHaveLength(2);
        expect(hook.result.current.currentSprint?.sprintId).toBe(2);

        // Transient failure (auth gap / network) → undefined response.
        nextResponse(undefined);
        await reload(hook);

        // Neither the cached list nor the selection is blanked out.
        expect(hook.result.current.projectSprints[PROJECT_ID]).toHaveLength(2);
        expect(hook.result.current.currentSprint?.sprintId).toBe(2);
    });
});
