// Database constants
export const DB_NAME = "genosData";
export const DB_VERSION = 4;

// LRU cap for the full-task cache (TASK_FULL store).
export const MAX_CACHED_FULL_TASKS = 500;

// Store names
export const STORES = {
    USER_INFO: "users",
    INBOX: "inbox",
    ACTIVITY_MESSAGES: "activityMessages",
    DM_CHATS: "dmChats",
    DM_MESSAGES: "dmMessages",
    DM_THREAD_MESSAGES: "dmThreadMessages",
    GM_CHATS: "gmChats",
    GM_MESSAGES: "gmMessages",
    GM_THREAD_MESSAGES: "gmThreadMessages",
    MDM_CHATS: "mdmChats",
    MDM_MESSAGES: "mdmMessages",
    MDM_THREAD_MESSAGES: "mdmThreadMessages",
    PM_CHATS: "pmChats",
    PM_MESSAGES: "pmMessages",
    PM_THREAD_MESSAGES: "pmThreadMessages",
    FLAGGED_MESSAGES: "flaggedMessages",
    TASK_META: "taskMeta",
    TASK_FULL: "taskFull",
    PERSONAL_NOTES: "personalNotes",
    TASK_NOTES: "taskNotes",
    CHAT_NOTES: "chatNotes",
    TODOS: "todos",
} as const;

// Key paths for object stores
export const KEY_PATHS = {
    USER_INFO: "userId",
    INBOX: "itemId",
    ACTIVITY_MESSAGES: "activityId",
    DM_CHATS: "chatId",
    DM_MESSAGES: "messageIdWithChatId",
    DM_THREAD_MESSAGES: "messageIdWithChatIdAndThreadId",
    GM_CHATS: "chatId",
    GM_MESSAGES: "messageIdWithChatId",
    GM_THREAD_MESSAGES: "messageIdWithChatIdAndThreadId",
    MDM_CHATS: "chatId",
    MDM_MESSAGES: "messageIdWithChatId",
    MDM_THREAD_MESSAGES: "messageIdWithChatIdAndThreadId",
    PM_CHATS: "chatId",
    PM_MESSAGES: "messageIdWithChatId",
    PM_THREAD_MESSAGES: "messageIdWithChatIdAndThreadId",
    FLAGGED_MESSAGES: "flaggedMessageId",
    TASK_META: "id",
    TASK_FULL: "id",
    PERSONAL_NOTES: "noteId",
    TASK_NOTES: "noteId",
    CHAT_NOTES: "noteId",
    TODOS: "todoId",
} as const;

// Index names
export const INDEX_NAMES = {
    USER_INFO: "UserInfoIndex",
    DM_CHATS: "DmTSLastMessageIndex",
    DM_MESSAGES: "DmMessagesIndex",
    DM_MESSAGES_COMPOUND: "DmMessagesCompoundIndex",
    DM_THREAD_MESSAGES: "DmThreadMessagesIndex",
    DM_THREAD_MESSAGES_COMPOUND: "DmThreadMessagesCompoundIndex",
    GM_CHATS: "GmTSLastMessageIndex",
    GM_MESSAGES: "GmMessagesIndex",
    GM_MESSAGES_COMPOUND: "GmMessagesCompoundIndex",
    GM_THREAD_MESSAGES: "GmThreadMessagesIndex",
    GM_THREAD_MESSAGES_COMPOUND: "GmThreadMessagesCompoundIndex",
    MDM_CHATS: "MdmTSLastMessageIndex",
    MDM_MESSAGES: "MdmMessagesIndex",
    MDM_MESSAGES_COMPOUND: "MdmMessagesCompoundIndex",
    MDM_THREAD_MESSAGES: "MdmThreadMessagesIndex",
    MDM_THREAD_MESSAGES_COMPOUND: "MdmThreadMessagesCompoundIndex",
    PM_CHATS: "PmTSLastMessageIndex",
    PM_MESSAGES: "PmMessagesIndex",
    PM_MESSAGES_COMPOUND: "PmMessagesCompoundIndex",
    PM_THREAD_MESSAGES: "PmThreadMessagesIndex",
    PM_THREAD_MESSAGES_COMPOUND: "PmThreadMessagesCompoundIndex",
    TASK_META: "TaskMetaIndex",
    TASK_META_COMPOUND: "TaskMetaCompoundIndex",
    TASK_FULL_LRU: "TaskFullLRUIndex",
    TODOS: "TodosUserIndex",
} as const;

// Index key paths
export const INDEX_KEY_PATHS = {
    USER_INFO: "teamId",
    DM_CHATS: "TSLastMessage",
    DM_MESSAGES: "chatId",
    DM_MESSAGES_COMPOUND: ["chatId", "messageIdWithChatId"],
    DM_THREAD_MESSAGES: "chatId",
    DM_THREAD_MESSAGES_COMPOUND: ["chatId", "threadId"],
    GM_CHATS: "TSLastMessage",
    GM_MESSAGES: "chatId",
    GM_MESSAGES_COMPOUND: ["chatId", "messageIdWithChatId"],
    GM_THREAD_MESSAGES: "chatId",
    GM_THREAD_MESSAGES_COMPOUND: ["chatId", "threadId"],
    MDM_CHATS: "TSLastMessage",
    MDM_MESSAGES: "chatId",
    MDM_MESSAGES_COMPOUND: ["chatId", "messageIdWithChatId"],
    MDM_THREAD_MESSAGES: "chatId",
    MDM_THREAD_MESSAGES_COMPOUND: ["chatId", "threadId"],
    PM_CHATS: "TSLastMessage",
    PM_MESSAGES: "chatId",
    PM_MESSAGES_COMPOUND: ["chatId", "messageIdWithChatId"],
    PM_THREAD_MESSAGES: "chatId",
    PM_THREAD_MESSAGES_COMPOUND: ["chatId", "threadId"],
    TASK_META: "projectId",
    TASK_META_COMPOUND: ["projectId", "status"],
    TASK_FULL_LRU: "accessedAt",
    TODOS: "userId",
} as const;
