import { ChatProps } from "../../../types/chat";

export const defaultChat: ChatProps = {
    chatId: -1,
    chatName: "Genos",
    chatType: -1,
    dmPartnerUser: {
        teamId: "",
        teamName: "",
        userId: "",
        userName: "",
        userEmail: "",
        avatarImgPath: "",
        tsLastSeen: "",
        tsJoined: "",
        customStatus: "",
    },
    latestMessageText: "",
    TSLastMessage: "",
    lastReadMessageId: -1,
    messages: [],
    latestMessage: {
        chatType: -1,
        systemUserId: "",
        messageIdWithChatId: "",
        chatId: -1,
        messageId: -1,
        content: [],
        contentText: "",
        sender: {
            teamId: "",
            teamName: "",
            userId: "",
            userName: "",
            userEmail: "",
            avatarImgPath: "",
            tsLastSeen: "",
            tsJoined: "",
            customStatus: "",
        },
        tsSent: "",
        tsUpdated: "",
        numReplies: 0,
        taskId: null,
        taskStatus: null,
    },
    isPrivate: false,
};
